-
  init:
    - git config --global core.autocrlf true

  build_script:
    - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1

  test: off

  branches:
    only:
      - develop