-
  init:
    - git config --global core.autocrlf true

  branches:
    only:
      - develop

  build_script:
    - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1

  test: off
-
  init:
    - git config --global core.autocrlf true

  branches:
    only:
      - master

  build_script:
    - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "Package"

  test: off  