# Build script
init:
  - git config --global core.autocrlf true

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop

# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1

# Branches to build
branches:
  # Whitelist
  only:
    - master

# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "Package"